services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - .:/app
    ports:
      - "4399:5000" # maps host 4399 --> container 5000
    # expose:
    #   - "5000"
    depends_on:
      - redis
    networks:
      - backend
    env_file:
      - .env.dev

 
  redis:
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - backend


  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs/selfsigned.crt:/etc/ssl/certs/nginx.crt:ro
      - ./nginx/certs/selfsigned.key:/etc/ssl/private/nginx.key:ro
    depends_on:
      - web
    networks:
      - backend

volumes:
  redis_data:

networks:
  backend: