services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    expose:
      - "5000"
    depends_on:
      - redis
    networks:
      - backend
    env_file:
      - .env
    restart: always


  redis:
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/prime.kines.umich.edu/fullchain.pem:/etc/letsencrypt/live/prime.kines.umich.edu/fullchain.pem
      - /etc/letsencrypt/live/prime.kines.umich.edu/privkey.pem:/etc/letsencrypt/live/prime.kines.umich.edu/privkey.pem
    depends_on:
      - web
    networks:
      - backend
    restart: always

volumes:
  redis_data:

networks:
  backend:
